import { spawn, spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";

const EMPTY_BAKED_REVISION = `/** Generated by scripts/stamp-revision.mjs. The committed value is empty. */
export const BAKED_REVISION = "";
`;

const FAKE_SHA = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
const BAKED_PATH = join(process.cwd(), "src/baked-revision.ts");
const STAMP = join(process.cwd(), "scripts/stamp-revision.mjs");

function runStamp(env: NodeJS.ProcessEnv = process.env) {
  const result = spawnSync(process.execPath, [STAMP], {
    cwd: process.cwd(),
    env,
    encoding: "utf8",
  });
  expect(result.status, result.stderr).toBe(0);
  return result;
}

function resolveGitSha(env: NodeJS.ProcessEnv = process.env) {
  const result = spawnSync(
    process.execPath,
    [
      "--input-type=module",
      "-e",
      "import { resolveGitSha } from './scripts/stamp-revision.mjs'; process.stdout.write(resolveGitSha());",
    ],
    { cwd: process.cwd(), env, encoding: "utf8" },
  );
  expect(result.status, result.stderr).toBe(0);
  return result.stdout;
}

describe("stamp-revision", () => {
  afterEach(() => {
    writeFileSync(BAKED_PATH, EMPTY_BAKED_REVISION);
  });

  it("prefers WORKERS_CI_COMMIT_SHA over git HEAD", () => {
    expect(
      resolveGitSha({ ...process.env, WORKERS_CI_COMMIT_SHA: FAKE_SHA }),
    ).toBe(FAKE_SHA);
  });

  it("falls back to git rev-parse HEAD", () => {
    const env = { ...process.env };
    delete env.WORKERS_CI_COMMIT_SHA;
    expect(resolveGitSha(env)).toMatch(/^[0-9a-f]{40}$/);
  });

  it("writes the SHA into src/baked-revision.ts", () => {
    runStamp({ ...process.env, WORKERS_CI_COMMIT_SHA: FAKE_SHA });
    expect(readFileSync(BAKED_PATH, "utf8")).toContain(
      `export const BAKED_REVISION = "${FAKE_SHA}";`,
    );
  });
});

describe("Workers Builds deploy path", () => {
  afterEach(() => {
    writeFileSync(BAKED_PATH, EMPTY_BAKED_REVISION);
  });

  it("embeds the stamped SHA when the deploy command is npx wrangler deploy", async () => {
    runStamp({ ...process.env, WORKERS_CI_COMMIT_SHA: FAKE_SHA });

    const outdir = mkdtempSync(join(tmpdir(), "nai-health-bundle-"));
    const wrangler = join(process.cwd(), "node_modules/wrangler/bin/wrangler.js");
    const result = await new Promise<{
      status: number | null;
      stdout: string;
      stderr: string;
    }>((resolvePromise) => {
      const child = spawn(
        process.execPath,
        [wrangler, "deploy", "--dry-run", "--outdir", outdir],
        { cwd: process.cwd() },
      );
      let stdout = "";
      let stderr = "";
      child.stdout.on("data", (chunk: Buffer) => {
        stdout += chunk.toString();
      });
      child.stderr.on("data", (chunk: Buffer) => {
        stderr += chunk.toString();
      });
      child.on("close", (status) => {
        resolvePromise({ status, stdout, stderr });
      });
    });

    const output = `${result.stdout}\n${result.stderr}`;
    try {
      expect(result.status, output).toBe(0);
      expect(output).toContain('env.NAI_BASE_URL ("https://text.novelai.net")');
      const bundle = readFileSync(join(outdir, "index.js"), "utf8");
      expect(bundle).toContain(FAKE_SHA);
      expect(bundle).toMatch(
        /BAKED_REVISION\s*=\s*"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/,
      );
    } finally {
      rmSync(outdir, { recursive: true, force: true });
    }
  }, 30_000);
});
